package com.androidxx.yangjw.day38_greendao_demo.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.androidxx.yangjw.day38_greendao_demo.dao.tb_user;

import com.androidxx.yangjw.day38_greendao_demo.dao.tb_userDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tb_userDaoConfig;

    private final tb_userDao tb_userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tb_userDaoConfig = daoConfigMap.get(tb_userDao.class).clone();
        tb_userDaoConfig.initIdentityScope(type);

        tb_userDao = new tb_userDao(tb_userDaoConfig, this);

        registerDao(tb_user.class, tb_userDao);
    }
    
    public void clear() {
        tb_userDaoConfig.clearIdentityScope();
    }

    public tb_userDao getTb_userDao() {
        return tb_userDao;
    }

}
