package com.androidxx.yangjw.day38_greendao_demo.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "TB_USER".
 */
@Entity
public class tb_user {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String name;
    private Integer age;

    @Generated(hash = 936343064)
    public tb_user() {
    }

    public tb_user(Long id) {
        this.id = id;
    }

    @Generated(hash = 1067407428)
    public tb_user(Long id, @NotNull String name, Integer age) {
        this.id = id;
        this.name = name;
        this.age = age;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

}
